[phases.setup]
nixPkgs = ["python310", "ffmpeg"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "gunicorn -w 2 -b 0.0.0.0:$PORT --chdir backend --timeout 300 app:app"
